### ISSUE TITLE
2 Y axis motors, one as inverted slave

### ISSUE THREAD

**Issue by markwbrown** [gnea/grbl-Mega#10]
I'm looking at the code and realized it doesn't seem to natively support two motors on one axis without using something like an external hex inverter.

I'm thinking that adding a Y2_STEP_BIT & Y_2_DIRECTION_BIT on the ports would work, as long as the step direction is inverted, right?

i.e. in cpu_map.h: 
 `  #define X_DIRECTION_BIT   7 // MEGA2560 Digital Pin 30`
`#define Y_DIRECTION_BIT   6 // MEGA2560 Digital Pin 31`
`#define Y2_DIRECTION_BIT   5 // MEGA2560 Digital Pin 32`
`#define Z_DIRECTION_BIT   4 // MEGA2560 Digital Pin 33`
`#define DIRECTION_MASK ((1<<X_DIRECTION_BIT)|1<<Y_DIRECTION_BIT)|(1<<Y2_DIRECTION_BIT)|(1<<Z_DIRECTION_BIT))`

To get the Y direction inverted for Y2, that seems a bit trickier as I'm not super familiar with the code base. Setting N_AXIS in nuts_bolts.h to 4 and modifying get_direction_pin_mask() in settings.c to:

`if ( axis_idx == Y_AXIS ) { return((1<<Y_DIRECTION_BIT)|(1<<~Y_DIRECTION_BIT)); }`

seems like it might work, but I wanted to see if anyone had some thoughts or sees a glaring deficiency in my approach.

**Comment by chamnit** [comment]
@markwbrown : The easiest way to make a second y axis stepper to move the opposite direction of the first is to flip the leads on one of the windings. So if one coil is wired + to -, the other motor would be - to +. This will make the second stepper rotate in the opposite direction. 

True. Having a setting to do this for you would be nice but I'm a little busy and this method has worked for years. It's standard wiring practice on all Grbl-based machines.
