### ISSUE TITLE
Does any hardware exist that uses the generic configuration?

### ISSUE THREAD

**Issue by bdurbrow** [gnea/grbl-Mega#112]
So, I'm looking to clean up the configuration system of my fork; and I went looking at the various hardware options (both for the standard version of Grbl and Grbl-Mega), and I didn't see any that actually could use the setup enabled by these:

```
#define DEFAULTS_GENERIC
#define CPU_MAP_2560_INITIAL

```

Did I miss something, or are these in fact unused in actual deployments of Grbl-Mega?

**Comment by chamnit** [comment]
No. Generic defaults are intentionally extremely conservative so users can see it working without having to tune it. In most cases, it works for this purpose.
