### ISSUE TITLE
Date format changed 

### ISSUE THREAD

**Issue by LETARTARE** [gnea/grbl-Mega#12]
1- in Uno

> grbl.h -> #define GRBL_VERSION_BUILD "20161219"
> => [VER:1.1d.20161025:]

2- in Mega

> grbl.h -> #define GRBL_VERSION_BUILD "20161219.3"
> => [VER:1.1d.20161025.x:]

Could you change the separator => [VER: 1.1d.20161025-x:] ? This simplifies detection.

Svn644 compiles correctly, good job.

**Comment by chamnit** [comment]
@LETARTARE : I needed some way to seperate multiple commits in one day. So I appended an incrementing value at the end.
