### ISSUE TITLE
Adaptive Multi-Axis Step-Smoothing(AMASS) levels vs DDS step generation and conversion details

### ISSUE THREAD

**Issue by shamsiqbal** [gnea/grbl-Mega#122]
Hi 
As grbl core is going to be on 32-bit route so i have question @chamnit  can you please put some lights on it that what is the difference in performance when use DDS as step Pulse generation instead Bresenham algorithm what are the pros and cons of it

**Comment by chamnit** [comment]
Bresenham is a more numerically stable algorithm as it only uses integers.
