### ISSUE TITLE
Serial comunication problem

### ISSUE THREAD

**Issue by EragonPower** [gnea/grbl-Mega#126]
I've recently encountered a problem regarding the serial comunication between my Arduino mega running grbl-mega and my computer: I've connected my Arduino to an USB port, opened the Arduino IDE serial terminal, and saw nothing, no serial comunication occurred nor TX/RX led blinking. I've tried another computer and another Arduino mega but nothing seems to work. Someone knows what courses this issue?

**Comment by fra589** [comment]
Hi @EragonPower,  
  
I recently have a similar issue on Windows 10 with an update who break all USB devices :-(  
cf. https://answers.microsoft.com/en-us/windows/forum/all/windows-10-pro-1909-breaks-all-usb-devices/33caa74b-a0bc-4389-a608-804c2099d170  
Perhaps you can search on [Google](https://www.google.com/search?q=windows+10+update+breaks+usb), it seams that it's not the first time this appear...
  
@++;  
Gauthier.

**Comment by EragonPower** [comment]
Is not a windows 10 problem, I've tried on a win 10 and a win 7 machine and nothing worked

**Comment by EragonPower** [comment]
The problem is that I've tried on a win 10 and a win 7 machine and nothing seems to work, I've even tried writing some code to test to test the serial read and write capability and everything worked, I think that there are some problems with my Arduino and the way that GRBL uses the serial comunication. Those problems manifested after powering up and using a VFD in a nearest electric cabinet so perhaps some magnetic fields may have damaged my Arduino but I'm not shore how, because again, the serial comunication works just fine except with GRBL

**Comment by EragonPower** [comment]
UPDATE: i managed to upload the .HEX version of GRBL on the arduino and now everything works

PS: after finding the solution I found the problem, arduinoIDE was not loading the GRBL-mega library, but rather a GRBL library that I had modified which had problems, after moving that corrupted library everything worked perfectly.
