### ISSUE TITLE
Nothing moves despite the OK returns.

### ISSUE THREAD

**Issue by manuel-masiello** [gnea/grbl-Mega#152]
Hello,

I am building a CNC machine with an Arduino Mega 2560, a CNC shield, 3 DRV8825 modules and 3 Nema 17.
I uploaded firmware grbl-Mega_v1.1f.20170802.hex but can't get it to work. The commands always return OK but nothing moves and the consumption is 0.75 A. The motor servos are blocked and refuse to move even by hand.

```
feeder> G91
feeder > G0 X1
feeder > G90
okay
okay

```

The problem does not seem to come from hardware because I tested by replacing the Arduino Mega with the Arduino Uno and the firmare grbl_v1.1h.20190825.hex and it works perfectly.

For my final assembly I need more free communication bus. That's why I have to use the Arduino Mega.

Can you tell me what's wrong?

Thank you

**Comment by manuel-masiello** [comment]
Hello,
I have just compiled the sources of the Mega version and the behavior is identical... 
Can we use the non-mega version?

**Comment by fra589** [comment]
Hello @manuel-masiello,  
  
What is your CNC shield?  
The grbl-Mega default shield is the RAMPS 1.4 board. This shield doesn't have the same pinout than the classical "Arduino CNC shield V3".
You need to modify the mapping definition in the cpu_map.h file to adjust the mapping of the grbl-Mega firmware to your shield.

@++;
Gauthier.

**Comment by manuel-masiello** [comment]
Hello @fra589 
Thx for your replay :-)

I use AZDelivery CNC Shield V3 Development Board for A4988. 
I will test with changing cpu_map.h.

Best,
Manuel

**Comment by manuel-masiello** [comment]
Hello @fra589 

Finally, I bought a RAMPS 1.4 card. However, I still can't get it to work. The firmware still responds OK but the motors don't move and they don't resist either. I have a consumption of 0.12A in 12Volt. I set the voltage of the DRV8825 to 0.7 Volts.

Picture of the assembly: 

https://i.ibb.co/d20tCLH/PXL-20220211-093435726-MP.jpg

I don't understand what I did wrong.

Thanks for your help.
Manuel

**Comment by golan11** [comment]
@manuel-masiello
I dont think you did anything wrong. according to these schemes:
[https://user-images.githubusercontent.com/26955383/34589604-dbd41b72-f16e-11e7-99a5-c91d116a0bd9.png](https://user-images.githubusercontent.com/26955383/34589604-dbd41b72-f16e-11e7-99a5-c91d116a0bd9.png)
[https://duino4projects.com/wp-content/uploads/2013/04/ardunio_mega_pinout.jpg](https://duino4projects.com/wp-content/uploads/2013/04/ardunio_mega_pinout.jpg)
The pins defined in the 'cpu_map.h' for the RAMP 1.4 are different from the actual connected ones.
My first thought was to just change the pins defined in the map file, but there this note in the comments:
// Define step pulse output pins. NOTE: All step bit pins must be on the same port.

But the connected pins are not in the same port:\ so I'm not sure how to go on. is this that critical? it seems like a pretty bad idea to connect the Mega to the RAMP with wire.
(I'm trying to do get a Mega and the ramps to function as a CNC controller as well).

**Comment by fra589** [comment]
Hi @manuel-masiello, @golan11,  
  
In config.h, you should comment the lines 37 & 38 like this:
```
//#define DEFAULTS_GENERIC
//#define CPU_MAP_2560_INITIAL
```
and uncomment lines 41 & 42 like this:
```
#define DEFAULTS_RAMPS_BOARD
#define CPU_MAP_2560_RAMPS_BOARD
```
to enable the correct port and pins definitions for the RAMPS board shield.

@++;
Gauthier.

**Comment by golan11** [comment]
@fra589 
Well I missed that the wrong pins are in a different board definition...
But after uploading with these lines uncommented (and the generic board and INITIAL commented), I don't get any response from the board. It looks like the upload went fine, but nothing get send or received from the serial port...
Previously I saw "GRBL 1.1 ... " or something similar when starting. now I get nothing.

**Comment by golan11** [comment]
OK I figured what I did wrong...
Turns out there was a grbl folder in my library folder that's in 'my Documents'...
Once I've replaced it with the one in this reop, the upload went fine and the motors are turning as expected :D
@manuel-masiello make sure that the correct library is in your main library folder

**Comment by guerillaengineer** [comment]
@golan11 thank you for this. I uploaded the grbl library to my Arduino ide then completely forgot about them in that location and was having a hell of a time editing files in a different folder, uploading, and wondering why nothing would be different.

you're my savior!

**Comment by manuel-masiello** [comment]
> OK I figured what I did wrong... Turns out there was a grbl folder in my library folder that's in 'my Documents'... Once I've replaced it with the one in this reop, the upload went fine and the motors are turning as expected :D @manuel-masiello make sure that the correct library is in your main library folder

Sorry for the late response. That works well. Thx.
