### ISSUE TITLE
pinout same as arduino uno? 

### ISSUE THREAD

**Issue by f0m3** [gnea/grbl-Mega#16]
_This is my first Issue ever so please correct me if i am doing it wrong!_
I compiled to mega version and uploaded to an arduino mega. I can communicate with grbl by universal gcode sender. But my old setup (i made a shield for my old arduino uno) doesnt work with the mega. Are the pinouts the same? If not this maybe should be mentioned on the wiki.

**Comment by chamnit** [comment]
@f0m3 : The pin out is different. A lot different. See the cpu_map.h file for wiring. There was a picture somewhere showing the pin layout, but it was never added to the Wiki.

**Comment by ff6347** [comment]
There is an issue for the pinout on the (old) original repo. https://github.com/grbl/grbl/issues/390. Would be great to have the images on the README

**Comment by 109JB** [comment]
> There is an issue for the pinout on the (old) original repo. grbl#390. Would be great to have the images on the README

There already is.

https://github.com/gnea/grbl-Mega/wiki/Connecting-Grbl-Mega

**Comment by ff6347** [comment]
Great. I didn't look into the wiki.
