### ISSUE TITLE
Help!! convert to GRBL **Spindle Connection. 

### ISSUE THREAD

**Issue by ashokavarthanan** [gnea/grbl-Mega#163]
I convert NC-studio controller to GRBL-Mega
Everything working expect "Spindle" On.

NC-studio controller has 3 pin  "H-M-L"  
(I don't know "H-M-L" working principle.)
High-Mid-Low
But I cannot control via GRBL controller.

when I connect "H" pin to 5v the Spindle is running 'Half Speed'.
Please Help.
Thanks.

**Comment by langwadt** [comment]
if you just want full speed, try all three pins 5V (or the spindle control pin)

**Comment by ashokavarthanan** [comment]
Thanks for replay. I will try. then replay.

**Comment by ashokavarthanan** [comment]
> if you just want full speed, try all three pins 5V (or the spindle control pin)

it works Thanks.
