### ISSUE TITLE
any reason for 1.9khz instead 1khz?

### ISSUE THREAD

**Issue by ariefadha** [gnea/grbl-Mega#170]
#define SPINDLE_PWM_MAX_VALUE 1024.0 // Translates to about 1.9 kHz PWM frequency at 1/8 prescaler

any reason why the default grbl-mega using 1.9khz while grbl just using 1khz and most chinese laser compatible with 1khz?

**Comment by fra589** [comment]
Hi @ariefadha,  
  
No, there is no particular reason...
This was the default from the gnea/grbl-Mega version which I used as a starting point for grbl-Mega-5X.

@++;
Gauthier.
