### ISSUE TITLE
Automate multiple lines of Gcode

### ISSUE THREAD

**Issue by M-Pioneers** [gnea/grbl-Mega#175]
How can I send G-Code directly using the code for the grbl library?

Is it like this?

```
#include <grbl.h>

void setup() {
  gc_execute_line("G00 X10");
}

void loop() {
  
}
```

When I connect the **atmega2560** to the charger, I want to run a few lines of Gcode automatically after starting grbl.

**Comment by fra589** [comment]
Hi @M-Pioneers,  

No you can't do it like that.

The grblUpload.ino sketch is just used to launch the compilation and upload from the Arduino IDE.
The Arduino IDE specific setup() and loop() functions are not used.

All the code is located in the grbl directory placed in the Arduino libraries folder.
The program's entry point is in the "main.c" file.
The main() function code initializes the entire system and then passes control to the main loop function protocol_main_loop() which is located in the "protocol.c" file.  

@++;
Gauthier.
