### ISSUE TITLE
DUAL AXIS on RAMPS board?

### ISSUE THREAD

**Issue by albmef** [gnea/grbl-Mega#177]
Hi 
Any chances that GRBL Mega bump to v1.1h so we could have the DUAL_AXIS feature on the mega+RAMPS as well ?
is this repo dead ?
best regards
bob

**Comment by fra589** [comment]
Hi bob,

This repo has not evolved for 6 years...
I took it over to create [grbl-Mega-5X](https://github.com/fra589/grbl-Mega-5X) which has the dual axis (axis cloning) functionality.

@++;
Gauthier.

**Comment by albmef** [comment]
merci Gauthier!
