### ISSUE TITLE
I want to connect Arduino Mega [4 pins / stepper / per axis] (look image) how ?!!!

### ISSUE THREAD

**Issue by savosik** [gnea/grbl-Mega#20]
![untitled-2](https://cloud.githubusercontent.com/assets/16825666/23376977/3ad89c58-fd3f-11e6-9577-5a15c0a6704c.jpg)

**Comment by langwadt** [comment]
you'll have to find enough pins and add the code to driver them and then you'll find that as draw on your picture it'll either be painfully slow or set the steppers on fire. You need constant current drive

**Comment by electrokean** [comment]
Use a proper stepper driver and save yourself a lot of frustration and smoke.
That said, there are unofficial ports of grbl that support direct motor drive - do a little searching on github, but keep in mind it is not recommended.
