### ISSUE TITLE
PWM frequency too low, motor noise

### ISSUE THREAD

**Issue by zygimantasmikulis** [gnea/grbl-Mega#23]
Hello how to change PWM frequency from 1.9khz to +-20khz? The problem is that then the frequency is lower my spindle motor generates hearable pitching noise and it is very anoying.

**Comment by chamnit** [comment]
Alter the spindle prescaler in cpu_map.h. If there isn't an option then change the prescaler in spindle_control.h. Read the 328p data sheet pn how to set it.
