### ISSUE TITLE
Possibility to redefine home location

### ISSUE THREAD

**Issue by Avalonnw** [gnea/grbl-Mega#24]
Hi, I'm using grbl mega with bcnc. I have limit switches installed and have home in back-right-top corner so it's sort of in compliance with "all-negative workspace". When arduino is just loaded and connected, it reports machine coordinates as 0,0,0. After home cycle the coordinates become -1,-1,-1. Is it possible to change these values to 0,0,0 or better 1,1,1?
bcnc guys told me it's a grbl thing but I could not find it myself so far.

**Comment by chamnit** [comment]
Yes. Enable the HOMING_FORCE_ORIGIN option in the config.h file. Recompile and flash.
