### ISSUE TITLE
The diagram says spindle PWM is on 7,, but it's next to the 4 pin

### ISSUE THREAD

**Issue by brakthehun** [gnea/grbl-Mega#36]
Which one is it??

**Comment by chamnit** [comment]
It's pin 7.

**Comment by chamnit** [comment]
![6de5c4d2-5d12-11e5-88e8-924d2951b633](https://user-images.githubusercontent.com/948029/29874229-5b70a31c-8d53-11e7-959a-cbcd025ab8b2.png)
