### ISSUE TITLE
grbl reboot after clicking on start

### ISSUE THREAD

**Issue by lukaslad** [gnea/grbl-Mega#37]
Helleo

 everyone

I have a big problem:
I use the grbl mega and i have a NEMA 17 stepper motor with an HY-DIV268N-5A Controller.
Sometimes it works but everytime when i start the Universal G-Code Sender, they is already in alarm mode.
If i type $X and trie to jog i get this error:

`Grbl 1.1f ['$' for help]
>>> $$
>>> $G
[MSG:'$H'|'$X' to unlock]
$0=255
$1=255
$2=255
$3=255
$4=1
$5=1
$6=1
$10=255
$11=2147483.648
$12=2147483.648
$13=1
$20=1
$21=1
$22=1
$23=255
$24=2147483.648
$25=2147483.648
$26=255
$27=2147483.648
$30=2147483648
$31=2147483648
$32=1
$100=2147483.648
$101=2147483.648
$102=2147483.648
$110=2147483.648
$111=2147483.648
$112=2147483.648
$120=2147483.648
$121=2147483.648
$122=2147483.648
$130=2147483.648
$131=2147483.648
$132=2147483.648
ok
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0.0 S0]
ok
>>> $J=G21G91Y8F10
(error:8) Grbl '$' command cannot be used unless Grbl is IDLE. Ensures smooth operation during a job.(error:8) Grbl '$' command cannot be used unless Grbl is IDLE. Ensures smooth operation during a job.`

If i try to load a g code and click on start the stepper motors dont move.
error:

`**** Connected to COM5 @ 115200 baud ****

Grbl 1.1f ['$' for help]
[MSG:'$H'|'$X' to unlock]
>>> $$
>>> $G
$0=255
$1=255
$2=255
$3=255
$4=1
$5=1
$6=1
$10=255
$11=2147483.648
$12=2147483.648
$13=1
$20=1
$21=1
$22=1
$23=255
$24=2147483.648
$25=2147483.648
$26=255
$27=2147483.648
$30=2147483648
$31=2147483648
$32=1
$100=2147483.648
$101=2147483.648
$102=2147483.648
$110=2147483.648
$111=2147483.648
$112=2147483.648
$120=2147483.648
$121=2147483.648
$122=2147483.648
$130=2147483.648
$131=2147483.648
$132=2147483.648
ok
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0.0 S0]
ok
>>> $X
[MSG:Caution: Unlocked]
ok
>>> G17
>>> G20
>>> G90
>>> G94
>>> G54
>>> M0
>>> M5
>>> M9
>>> G0Z0.25F5
>>> X-0.5Y0.
ok
>>> G1Z0.
Skipping command #14
>>> G2X0.Y-0.5I0.5J0.
>>> G2X-0.5Y0.I0.J0.5
ok
ok
ok
ok`

then the active state is HOLD and i cant do anything

The only way to bring them in action is to click on return to zero. that work one time and then i must unplug and plug again the arduino.

i used pin 24 for PUL+, pin 25 for pul+, pin 30 and 31 for dir+
enove power is also there.

please help me fast :-)
Greetings Lukas

**Comment by chamnit** [comment]
Your settings are all mangled. Reset them by commanding a `$RST=*`.
