### ISSUE TITLE
Real-time adjustable feedrates

### ISSUE THREAD

**Issue by quangvi** [gnea/grbl-Mega#4]
sorry, i'm not good in write English
i waiting for Real-time adjustable feedrates and rapids overrides in version 1.0 , but it,s so long time
i had write Backlash compensation so good, but Real-time adjustable feedrates and rapids overrides so difficult.
can't you help me ?,

**Comment by chamnit** [comment]
@quangvi : You'll have to wait until it's released.

**Comment by quangvi** [comment]
thank you for repply
