### ISSUE TITLE
question about the download zip contents

### ISSUE THREAD

**Issue by splitn2** [gnea/grbl-Mega#5]
Hi , I downloaded the zip file grbl-Mega.edge and I see under the grbl folder there is a "examples" folder. Is this "examples" required to be imported into the IDE ? Thanks

**Comment by chamnit** [comment]
@splitn2 : Sort of. The examples folder contains the .INO file to perform the compile and upload, but it only contains a `#include <grbl.h>` line in it. A new sketch with that line (and only that line) will do the same thing.
