### ISSUE TITLE
Compile for windows

### ISSUE THREAD

**Issue by JosephusMiller** [gnea/grbl-Mega#54]
Hi,

after >1 hour trying to install the GRBL libs through the Arduino IDE I somewhere found a description to simply 
- copy the grbl folder to the libraries,
- restart the ide
- ready for compilation.

Worked instantly. 

I think this should be mentioned on the installation / compile section in the grbl wiki. At least as an alternative. 

Best regards,
JM.

**Comment by chamnit** [comment]
The wiki instructions basically do the same thing. There is some extra instructions that are there to prevent common errors, like not updating the IDE or not removing an old Grbl installation.

**Comment by Chrominator** [comment]
The wiki instructions did not made the job for me, IDE complaining about the missing .zip.
The procedure described by JosephusMiller actually works and it avoids to loose more time on compiling grbl-mega.
