### ISSUE TITLE
PWM on Ramps with grbl-MEGA not working.  Only 0 to 5 volts nothing in between...

### ISSUE THREAD

**Issue by bigshug** [gnea/grbl-Mega#55]
Hey folks.  I can’t get PWM to function properly on Sainsmart RAMPS Mega2560 board with grbl-Mega.

First off - I’m checking output on D11.  Correct pin for RAMPS?  (I guess not but can't find any other pin that gives me 5 volts when sending an M3)

It’s all or nothing - 0 or 5 volts.  I can switch it on and off with M3 and M5 but get no change when changing the S value.

I’ve been through the config.h spindle settings and checked cpu_map.h but nothing fixes this issue.

Everything works as it should on an UNO with normal GRBL but it would be useful to get some use out of this board.

Any ideas on how to sort this before this board is consigned to the parts bin?

Cheers

**Comment by bigshug** [comment]
Ok.  Reflashed and now get different results - why I do not know...

D11 = is now 0.1v
D6   M4 gives 5v  - M3 turns it off - but M5 doesn’t switch it off - (I guess this is spindle direction?)
D5  M3 and M4 give 5v - M5 turns off.

**Comment by bigshug** [comment]
ok -so it looks like PIN 8 is the spindle PWM output - although I get nothing from it.  I think it's the hot bed output on this board.

How do I define another PWM pin for testing purposes?  Will I need to change the register values too?  

Yes I am in way over my head but really want to figure this out now :o)

**Comment by bigshug** [comment]
Right then.  Sorted.  Pin 8 is indeed the PWM pin.  However it is 12v when the board is externally powered and I'm after 0 - 5volts.  There is 5 volts going to the mosfet - I guess this is the real D8.  Will trace it back somewhere and take a feed off it.

**Comment by chamnit** [comment]
@bigshug : The Arduino Mega does not operate at 12V. If you are reading 12V, you are doing something wrong or something is wrong with your board. It should be 0V to 5V. 

FYI, cpu_map.h contains the pin configuration and shows you that D8 is the PWM pin.

**Comment by bigshug** [comment]
The board is a 'Sainsmart all in one' that can be powered externally - I guess for high power heated bed etc.  It gives a 12v PWM output at the 'BED' terminal or 5v PWM on D8 going into the FET.  It's a nice board so glad it's now working.
![615q98yjevl _sx385_ copy](https://user-images.githubusercontent.com/30386552/38202410-7517ddfa-3693-11e8-93d1-ccb7440274e9.jpg)

Incidentally - I've no idea why it wasn't working immediately.   Clearly I'd changed something in the GRBL settings but don't recall doing so.  It might have started working after doing the reset - $RST=*

**Comment by bigshug** [comment]
See comment here about 12v - https://github.com/gnea/grbl-Mega/issues/11#issuecomment-311184454

**Comment by rasciodc** [comment]
**0-5V PWM on Pin D6:**

I know this issue is closed, but, just in case someone else comes accross the same need of having a 0-5V PWM pin to control the Spindle, here is the code to have it working on pin D6 (Servo 2 on RAMPS). This should replace lines 259 to 283 on cpu_map.h:
```
// Advanced Configuration Below You should not need to touch these variables
  // Set Timer up to use TIMER4C which is attached to Digital Pin 6 - Ramps Servo 2
  #define SPINDLE_PWM_MAX_VALUE     255.0 // Since it's a 8bit timer
  #ifndef SPINDLE_PWM_MIN_VALUE
  #define SPINDLE_PWM_MIN_VALUE   1   // Must be greater than zero.
  #endif
  #define SPINDLE_PWM_OFF_VALUE     0
  #define SPINDLE_PWM_RANGE         (SPINDLE_PWM_MAX_VALUE-SPINDLE_PWM_MIN_VALUE)

  #define SPINDLE_TCCRA_REGISTER    TCCR4A
  #define SPINDLE_TCCRB_REGISTER    TCCR4B
  #define SPINDLE_OCR_REGISTER      OCR4A
  #define SPINDLE_COMB_BIT          COM4A1

  #define SPINDLE_TCCRA_INIT_MASK (1<<WGM41)
  #define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) | (1<<CS41)) 
  #define SPINDLE_OCRA_REGISTER   ICR4 
  #define SPINDLE_OCRA_TOP_VALUE  0xFF // PWM counter reset value. Should be the same as PWM_MAX_VALUE in hex.

  // Define spindle output pins.
  #define SPINDLE_PWM_DDR   DDRH
  #define SPINDLE_PWM_PORT  PORTH
  #define SPINDLE_PWM_BIT   3 // MEGA2560 Digital Pin 6
```

Cheers!

**Comment by luisluna2** [comment]
Hello friends, I have a question, how make 3 PWM with D8, D9 and D10?

**Comment by JeffHank1** [comment]
A Big Thanks to rasciodc for figuring this solution out and Posting it. It was very easy to cut and paste the solution into the appropriate file, recompile in Arduino IDE, create a Hex file and Upload it to my Arduino Mega 2560 with Xloader. Easy. Works perfectly with my 12V laser that wants a 5V TTL control signal.

**Comment by ksdfpr** [comment]
> 
> 
> **0-5V PWM on Pin D6:**
> 
> I know this issue is closed, but, just in case someone else comes accross the same need of having a 0-5V PWM pin to control the Spindle, here is the code to have it working on pin D6 (Servo 2 on RAMPS). This should replace lines 259 to 283 on cpu_map.h:
> 
> ```
> // Advanced Configuration Below You should not need to touch these variables
>   // Set Timer up to use TIMER4C which is attached to Digital Pin 6 - Ramps Servo 2
>   #define SPINDLE_PWM_MAX_VALUE     255.0 // Since it's a 8bit timer
>   #ifndef SPINDLE_PWM_MIN_VALUE
>   #define SPINDLE_PWM_MIN_VALUE   1   // Must be greater than zero.
>   #endif
>   #define SPINDLE_PWM_OFF_VALUE     0
>   #define SPINDLE_PWM_RANGE         (SPINDLE_PWM_MAX_VALUE-SPINDLE_PWM_MIN_VALUE)
> 
>   #define SPINDLE_TCCRA_REGISTER    TCCR4A
>   #define SPINDLE_TCCRB_REGISTER    TCCR4B
>   #define SPINDLE_OCR_REGISTER      OCR4A
>   #define SPINDLE_COMB_BIT          COM4A1
> 
>   #define SPINDLE_TCCRA_INIT_MASK (1<<WGM41)
>   #define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) | (1<<CS41)) 
>   #define SPINDLE_OCRA_REGISTER   ICR4 
>   #define SPINDLE_OCRA_TOP_VALUE  0xFF // PWM counter reset value. Should be the same as PWM_MAX_VALUE in hex.
> 
>   // Define spindle output pins.
>   #define SPINDLE_PWM_DDR   DDRH
>   #define SPINDLE_PWM_PORT  PORTH
>   #define SPINDLE_PWM_BIT   3 // MEGA2560 Digital Pin 6
> ```
> 
> Cheers!

Nice! Could you help me with another board? (GT2560) What have I to change to work with any of the bed pins?

**Comment by thesalcedo** [comment]
> A Big Thanks to rasciodc for figuring this solution out and Posting it. It was very easy to cut and paste the solution into the appropriate file, recompile in Arduino IDE, create a Hex file and Upload it to my Arduino Mega 2560 with Xloader. Easy. Works perfectly with my 12V laser that wants a 5V TTL control signal.

@JeffHank1 for this to work, does the laser 12V power need to come from the RAMPS +12V output (D8)? Since the - is shared? I was planning on powering my Laser controller externally.

**Comment by fedex000000000001** [comment]
> **0-5V PWM en pin D6:**
> 
> Sé que este problema está cerrado, pero, en caso de que alguien más tenga la misma necesidad de tener un pin PWM de 0-5V para controlar el eje, aquí está el código para que funcione en el pin D6 (Servo 2 en RAMPS). Esto debería reemplazar las líneas 259 a 283 en cpu_map.h:
> 
> ```
> // Advanced Configuration Below You should not need to touch these variables
>   // Set Timer up to use TIMER4C which is attached to Digital Pin 6 - Ramps Servo 2
>   #define SPINDLE_PWM_MAX_VALUE     255.0 // Since it's a 8bit timer
>   #ifndef SPINDLE_PWM_MIN_VALUE
>   #define SPINDLE_PWM_MIN_VALUE   1   // Must be greater than zero.
>   #endif
>   #define SPINDLE_PWM_OFF_VALUE     0
>   #define SPINDLE_PWM_RANGE         (SPINDLE_PWM_MAX_VALUE-SPINDLE_PWM_MIN_VALUE)
> 
>   #define SPINDLE_TCCRA_REGISTER    TCCR4A
>   #define SPINDLE_TCCRB_REGISTER    TCCR4B
>   #define SPINDLE_OCR_REGISTER      OCR4A
>   #define SPINDLE_COMB_BIT          COM4A1
> 
>   #define SPINDLE_TCCRA_INIT_MASK (1<<WGM41)
>   #define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) | (1<<CS41)) 
>   #define SPINDLE_OCRA_REGISTER   ICR4 
>   #define SPINDLE_OCRA_TOP_VALUE  0xFF // PWM counter reset value. Should be the same as PWM_MAX_VALUE in hex.
> 
>   // Define spindle output pins.
>   #define SPINDLE_PWM_DDR   DDRH
>   #define SPINDLE_PWM_PORT  PORTH
>   #define SPINDLE_PWM_BIT   3 // MEGA2560 Digital Pin 6
> ```
> 
> ¡Salud!


hello, do i have to enable $32 = 1 in grbl to use the PWN of pin d6 ?

**Comment by luisluna2** [comment]
Te agradezco mucho tu apoyo y atención, lo estaré probando en la semana, muchísimas gracias.

¡Feliz inicio de Año 2023!
________________________________
