### ISSUE TITLE
Jerk relief 

### ISSUE THREAD

**Issue by MARIOBASZ** [gnea/grbl-Mega#60]
Could you implement some jerk relief by adding some intermediate point (or more) in the trapezoidal profile of acceleration?
I think something like acceleration is a part (example 1/3) of the established to reach a certain speed and between this speed and zero.
For trochoidal cutting mode it would be good to increase the acceleration with fewer jerks.

image

**Comment by chamnit** [comment]
Please do everyone a favor and not post the same question in multiple places.
