### ISSUE TITLE
Spindle PWM not working in laser mode

### ISSUE THREAD

**Issue by maxpautsch** [gnea/grbl-Mega#61]
The PWM output for the spindle seems not to work in laser mode. (CPU_MAP_2560_INITIAL and also CPU_MAP_2560_RAMPS_BOARD)
Working as expected in normal mode.

**Comment by chamnit** [comment]
How so? Laser mode does not turn on its output in G0 motions for safety reasons.

**Comment by maxpautsch** [comment]
Sorry. Was user trubble ;)
