### ISSUE TITLE
PWM Speeds

### ISSUE THREAD

**Issue by readymotion** [gnea/grbl-Mega#66]
On the uno we can pick the kHz we want for our PWM timers
62.5
7.8
1.96
.98

How can i set the mega to run at 62.5 kHz PWM?
Thanks,
Ryan

**Comment by chamnit** [comment]
I think all you have to do is change the prescalars, like the 328p version does. I'm unsure what the macros are for it. They are available in the data sheet though.

**Comment by readymotion** [comment]
So this the UNO's
  #define SPINDLE_TCCRA_INIT_MASK   ((1<<WGM20) | (1<<WGM21))  // Configures fast PWM mode.
  // #define SPINDLE_TCCRB_INIT_MASK   (1<<CS20)               // Disable prescaler -> 62.5kHz

Mega's
  // 1/8 Prescaler, 16-bit Fast PWM mode
  #define SPINDLE_TCCRA_INIT_MASK ((1<<WGM40) | (1<<WGM41))
  #define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) | (1<<CS41)) 


Would I just change the  | (1<<CS41))  to   (1<<CS20)  ? Or CS40

Thanks for the help!!!

**Comment by Delphi** [comment]
Pardon me for resurrecting an old thread, I too had issues with the default PWM at 1.96khz for a laser that supports a 5khz-25khz input range.

After a couple of hours of searching and experimenting, I modified the cpu_map.h  at line 124, by commenting out the default and adding a new line.

// #define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) | (1<<CS41)) //default 1.96khz
#define SPINDLE_TCCRB_INIT_MASK ((1<<WGM42) | (1<<WGM43) )  //modified ~15.6khz

Sadly I dont know what combination of values can be used to obtain other PWM frequencies, although I hope this helps the next person.

Thanks.
