### ISSUE TITLE
Merging changes of gnea/grbl together?

### ISSUE THREAD

**Issue by Fusseldieb** [gnea/grbl-Mega#67]
Hi,
it would be nice if someone could merge the two together to fix some bugs and things that were fixed in gnea/grbl (the original).

I saw changes in gnea/grbl from 2 months ago and changes in this repo from 1 year ago, so it is some versions/fixes behind.

I would love to see that (or know how to merge both together locally)

Thanks in advance.

**Comment by chamnit** [comment]
My fault. I'll be doing this pretty soon.  I also have a couple of things I need to add to the Mega repo at the same time.

**Comment by chamnit** [comment]
@Fusseldieb : Just added the upstream changes. Please test. I haven't had the time to do so.
