### ISSUE TITLE
which g-code sender is being used in grbl-Mega testing?

### ISSUE THREAD

**Issue by splitn2** [gnea/grbl-Mega#7]
I'm using UGS 1.0.9 but I am wondering which sender and build is being used in development/testing ? Seems to be working at least running gcode through so I'll hook up some drivers and steppers and test soon hopefully. cheers

just uploaded 2.0 classic (latest build oct 2nd)  seems to work too. The UGS Platform looks good too but it started behaving weird so I went and loaded latest classic build.

**Comment by chamnit** [comment]
@splitn2 : Grbl-Mega doesn't contain anything significantly different than the mainstream Grbl v0.9. Using UGS or any other GUI should work fine.
