### ISSUE TITLE
g-code start from selected line

### ISSUE THREAD

**Issue by manisaranbala** [gnea/grbl-Mega#71]
my machine running 75% than cutter broken.  than again start first line running.  how to
skip 75% g-code command  don't edit g-code   

pl tel me my email id vstveeramani@gmail.com
how to run g-code start from selected line

**Comment by swarfer** [comment]
if you are using bCNC then you can disable blocks in the editor.
disabled blocks are not deleted, they just don't get used in the current run.

**Comment by chamnit** [comment]
You have to be very careful with resuming jobs. You have to ensure the g-code state is exactly where it's supposed to be when you restart at a random line. It's best to run Grbl in check mode up to the line before the restart. Record the g-code state. Restart the job at the resume line after you set the g-code state correctly. Most GUIs require this to be done manually. Not sure if bCNC has automated this process or not.

**Comment by manisaranbala** [comment]
@swarfer thanks. Bro i used g-code2grbl
Android app
