### ISSUE TITLE
Continous toggle into Hold state

### ISSUE THREAD

**Issue by macdroid53** [gnea/grbl-Mega#85]
I now have 1.1f installed on my Mega.

With the UGCS gui open grbl continuously toggles into Hold state.

If I hit Cancel or Resume it toggles to Idle, then immediately back to Hold.

If I just watch (i.e. click nothing) it will toggle to Idle then back to Hold. This repeats continuously.

**Comment by macdroid53** [comment]
Just replaced the mega with an UNO, uploaded uno version of 1.1f and it works fine...

**Comment by chamnit** [comment]
There isn’t anything that would cause this issue in Grbls side, unless there was some kind of EMI or waiting fault in the hold and resume input pins. Check those pins for any issues.

**Comment by macdroid53** [comment]
I checked all limit inputs and the reset input (nothing connected to the rest) with my o'scope and found no glitches or appreciable noise spikes.

It's a well used Mega so maybe it's just tired. As I said, I replaced it with an Uno and all seems to work fine. Gcode files that just went wonky on the Mega, now work fine.

**Comment by chamnit** [comment]
K. Thanks for the feedback. I'll keep an eye out on any other random instability reports like this one, but you're probably right that it's your Mega being wonky.
